

export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL';
export const DELETE_POST = 'DELETE_POST';
export const CREATE_POST = 'CREATE_POST';
export const  CREATE_POST_SUCCESS = ' CREATE_POST_SUCCESS';
export const  CREATE_POST_FAIL = ' CREATE_POST_FAIL';
export const  ADD_POST = ' ADD_POST';
export const  EDIT_POST = ' EDIT_POST';
export const   EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS';
export const   EDIT_POST_FAIL = 'EDIT_POST_FAIL,';


export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';


export const FETCH_USER_ALBUMS_REQUEST = 'FETCH_USER_ALBUMS_REQUEST';
export const FETCH_USER_ALBUMS_SUCCESS = 'FETCH_USER_ALBUMS_SUCCESS';
export const FETCH_USER_ALBUMS_FAILURE = 'FETCH_USER_ALBUMS_FAILURE';

export const FETCH_USER_TODOS_REQUEST = 'FETCH_USER_TODOS_REQUEST';
export const FETCH_USER_TODOS_SUCCESS = 'FETCH_USER_TODOS_SUCCESS';
export const FETCH_USER_TODOS_FAILURE = 'FETCH_USER_TODOS_FAILURE';
